### PR TITLE
Make Push Resolve

### PR DESCRIPTION
**Pull request by popeeyy**
Make the push resolve so the speak promise resolves when the assistant is done speaking.

### CODE REVIEW

**Review by taeukkang — CHANGES_REQUESTED** [review]
Thanks! Just a small thing, but can you add a semicolon at the end of line 104? Will merge after that.

**Comment by popeeyy** [comment]
I made sure the audio finished playing before resolving and added that semicolon.

**Review by taeukkang — COMMENTED** [review]
Thanks for the quick response! I think that the `setTimeout` is unnecssary because the duration wouldn't be accurate (Google Home/Chromecast may be overridden with another command or stream) and the script's goal is to push media so after pushing the audio, it would make the most sense to resolve it. It would also block other code executions. 

I think if a wait is necessary, it would be the best to do it outside of this library so that it doesn't add extra complication. I'm open to other opinions as well.

**Comment by popeeyy** [comment]
I use it in my code on my own version to queue through the messages I want to send. There's no other way to tell when a message ends, maybe it should resolve the status so they can do it on their own?

**Comment by taeukkang** [comment]
Yeah, returning the whole status object would make more sense and then have users implement delays on their own since pushing media would remain async.

**Review by taeukkang — APPROVED** [review]

**Pull request merged**
